name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DAY_OF_WEEK: Monday

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing my packages
        run: yarn

      - name: Build my App
        run: yarn build
        env:
          NEXT_PUBLIC_BASE_PATH: /portifolio
      - run: npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /portifolio
      - run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
